{{- if .Values.agent }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dakr.fullname" . }}-agent-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dakr.fullname" . }}-agent-role
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    verbs: ["*"]
    resources:
      - nodes/log
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
  - apiGroups: [ "" ]
    resources: ["nodes/proxy", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dakr.fullname" . }}-agent-crb
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dakr.fullname" . }}-agent-role
subjects:
- kind: ServiceAccount
  name: {{ include "dakr.fullname" . }}-agent-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
