apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workloadrecommendations.dakr.devzero.io
spec:
  group: dakr.devzero.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              recommendationId:
                type: string
              workloadUid:
                type: string
              namespace:
                type: string
              kind:
                type: integer
                enum: [0, 1, 2, 3, 4, 5, 6, 7, 8]
              name:
                type: string
              containerRecommendations:
                type: array
                items:
                  type: object
                  properties:
                    containerName:
                      type: string
                    recommendedRequest:
                      type: object
                      properties:
                        cpu:
                          type: integer
                          format: int64
                        memory:
                          type: integer
                          format: int64
                    recommendedLimit:
                      type: object
                      properties:
                        cpu:
                          type: integer
                          format: int64
                        memory:
                          type: integer
                          format: int64
              replicaCount:
                type: integer
                format: int32
              priority:
                type: integer
                format: int32
                default: 0
              autoApply:
                type: boolean
                default: true
            required:
            - recommendationId
            - workloadUid
            - namespace
            - kind
            - name
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Applying", "Applied", "Failed", "Skipped"]
              message:
                type: string
              appliedAt:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              observedGeneration:
                type: integer
                format: int64
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: workloadrecommendations
    singular: workloadrecommendation
    kind: WorkloadRecommendation
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodegrouprecommendations.dakr.devzero.io
spec:
  group: dakr.devzero.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              recommendationId:
                type: string
              nodeGroupName:
                type: string
              nodesToRemove:
                type: array
                items:
                  type: string
              priority:
                type: integer
                format: int32
                default: 0
              autoApply:
                type: boolean
                default: true
            required:
            - recommendationId
            - nodeGroupName
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Applying", "Applied", "Failed", "Skipped"]
              message:
                type: string
              appliedAt:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              observedGeneration:
                type: integer
                format: int64
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Cluster
  names:
    plural: nodegrouprecommendations
    singular: nodegrouprecommendation
    kind: NodeGroupRecommendation 