{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "dakr.fullname" . }}
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "dakr.fullname" . }}.{{ .Release.Namespace }}.io
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - {{ .Release.Namespace }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "dakr.fullname" . }}-operator
        path: /mutate
        port: 443
      caBundle: {{ .Values.webhook.caBundle }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
{{- end }} 